import { SystemStyleObject } from '@chakra-ui/react';

export const SignUpFormStyles: Record<string, SystemStyleObject> = {
  formContainer: {
    width: '100%',
    minHeight: 'calc(100vh - 4.5rem)',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    bg: 'gray.50',
    py: '2rem',
  },
  formWrapper: {
    width: {
      base: '95%',
      sm: '450px',
    },
    p: '2.5rem',
    flexDirection: 'column',
    bg: 'white',
    borderRadius: 'xl',
    boxShadow: 'xl',
    border: '1px solid',
    borderColor: 'gray.100',
    gap: '15px',
  },
  formControl: {
    width: '100%',
  },
  title: {
    color: 'blue.800',
    fontFamily: 'Open Sans',
    fontWeight: '700',
    fontSize: '1.8rem',
    textAlign: 'center',
    mb: '1rem',
  },
  formLabel: {
    fontSize: '0.9rem',
    fontWeight: '600',
    color: 'gray.700',
    mb: '0.4rem',
  },
  input: {
    height: '2.8rem',
    borderRadius: 'md',
    bg: 'white',
    border: '1px solid',
    borderColor: 'gray.200',
    _hover: { borderColor: 'gray.300' },
    _focus: { borderColor: 'blue.500', boxShadow: '0 0 0 1px #3182ce' },
  },
  inputPasswordWrapper: {
    position: 'relative',
    width: '100%',
  },
  inputPassword: {
    width: '100%',
    height: '2.8rem',
    borderRadius: 'md',
    bg: 'white',
    border: '1px solid',
    borderColor: 'gray.200',
    _hover: { borderColor: 'gray.300' },
    _focus: { borderColor: 'blue.500', boxShadow: '0 0 0 1px #3182ce' },
  },
  eyeIcon: {
    boxSize: '20px',
    position: 'absolute',
    right: '12px',
    top: '12px',
    cursor: 'pointer',
    color: 'gray.400',
    _hover: { color: 'gray.600' },
  },
  formErrorMessage: {
    fontSize: '0.75rem',
    mt: '0.2rem',
  },
  buttonWrapper: {
    width: '100%',
    flexDirection: 'column',
    gap: '1.5rem',
    mt: '1.5rem',
  },
  button: {
    width: '100%',
    height: '2.8rem',
    borderRadius: 'md',
    fontSize: '1rem',
    fontWeight: '600',
    color: '#ffffff',
    backgroundColor: 'blue.500',
    _hover: { bg: 'blue.600' },
    transition: 'all 0.2s',
  },
  adviceContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '4px',
  },
  textAdvice: {
    fontSize: '0.85rem',
    color: 'gray.500',
    marginRight: '10px',
  },
  link: {
    fontSize: '0.85rem',
    fontWeight: '600',
    color: 'blue.500',
    _hover: { textDecoration: 'underline' },
  },
};
