import { SystemStyleObject } from '@chakra-ui/react';

export const EmployeeFormStyles: Record<string, SystemStyleObject> = {
  formContainer: {
    width: '100%',
    height: '72rem',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  formWrapper: {
    width: {
      base: '97%',
      sm: '90%',
      md: '70%',
      lg: '60%',
      xl: '50%',
      '2xl': '40%',
    },
    height: '72rem',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: '1rem',
    boxShadow:
      'rgba(0, 0, 0, 0.1) 0px 4px 6px -1px, rgba(0, 0, 0, 0.06) 0px 2px 4px -1px;',
  },
  formControl: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
  },

  title: {
    color: '#1479ff',
    fontFamily: 'Montserrat',
    fontWeight: '500',
    fontSize: '2rem',
    margin: '1rem 0',
  },
  formLabel: {
    alignSelf: 'start',
    fontSize: '1.1rem',
    fontFamily: 'Montserrat',
    ml: '10%',
    mb: '0.2rem',
  },
  formControllWrapper: {
    alignSelf: 'start',
    ml: '10%',
    w: '80%',
  },
  formLabelStatus: {
    fontSize: '1.1rem',
    fontFamily: 'Montserrat',
    mb: '0.2rem',
  },
  formLabelAvatar: {
    fontSize: '1.1rem',
    fontFamily: 'Montserrat',
    mb: '0.2rem',
    display: {
      base: 'none',
      sm: 'block',
    },
  },
  circleUpload: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '5rem',
    height: '5rem',
    alignSelf: 'start',
    fontFamily: 'Montserrat',
    color: '#011627',
    bg: '#d5e6ff',
    borderRadius: '50%',
    padding: '0.5rem',
    border: '2px solid #1479ff',
    cursor: 'pointer',
    _hover: {
      transform: 'scale(0.95)',
      transition: 'ease-in 0.1s',
    },
  },
  imageUpload: {
    borderRadius: '50%',
    width: '5rem',
    height: '5rem',
    cursor: 'pointer',
  },
  input: {
    width: '80%',
    height: '2.5rem',
    fontFamily: 'Montserrat',
    borderRadius: '0.3rem',
    borderColor: '#d5e6ff',
    bg: '#E5F0FF',
    _hover: { bg: '#d5e6ff' },
    _focus: { bg: 'ffffff', borderColor: '#1479ff' },
    pl: '0.3rem',
    boxShadow: 'rgba(0, 0, 0, 0.1) -4px 9px 25px -6px;',
  },
  formErrorWrapper: {
    display: 'flex',
    justifyContent: 'center',
    width: '80%',
    height: '1.5rem',
  },
  formErrorMessage: {
    fontFamily: 'Montserrat',
    fontSize: '14px',
  },
  buttonWrapper: {
    width: '80%',
    height: '3rem',
    alignItems: 'center',
    justifyContent: 'space-between',
    mt: {
      base: '0',
      s: '1rem',
    },
  },
  button: {
    width: '45%',
    height: '2.5rem',
    borderRadius: '0.3rem',
    fontSize: '1.3rem',
    color: '#ffffff',
    backgroundColor: '#193b68',
    _hover: { bg: '#245494' },
    _focus: { bg: '#193b68' },
    transition: 'ease 0.1s',
  },
  buttonBack: {
    width: '45%',
    height: '2.5rem',
    borderRadius: '0.3rem',
    fontSize: '1.3rem',
    color: '#193b68',
    backgroundColor: '#fff',
    _hover: { bg: '#CCDCF5' },
    _focus: { bg: '#CCDCF5' },
    transition: 'ease 0.1s',
    border: '2px solid #193b68',
  },
  select: {
    height: '2.5rem',
    fontFamily: 'Montserrat',
    borderRadius: '0.3rem',
    borderColor: '#d5e6ff',
    bg: '#E5F0FF',
    _hover: { bg: '#d5e6ff' },
    _focus: { bg: 'ffffff', borderColor: '#1479ff' },
    pl: '0.3rem',
    boxShadow: 'rgba(0, 0, 0, 0.1) -4px 9px 25px -6px;',
    cursor: 'pointer',
  },
};
