import { SystemStyleObject } from '@chakra-ui/react';

export const EmployeeFormStyles: Record<string, SystemStyleObject> = {
  formContainer: {
    width: '100%',
    flexDirection: 'column',
  },
  formWrapper: {
    width: '100%',
    flexDirection: 'column',
    gap: '1.5rem',
  },
  sectionTitle: {
    fontSize: '0.9rem',
    fontWeight: '700',
    color: 'blue.500',
    textTransform: 'uppercase',
    letterSpacing: 'wider',
    mb: '1rem',
    pb: '0.5rem',
    borderBottom: '1px solid',
    borderColor: 'gray.100',
  },
  formControl: {
    width: '100%',
  },
  formLabel: {
    fontSize: '0.9rem',
    fontWeight: '600',
    color: 'gray.700',
    mb: '0.4rem',
  },
  input: {
    height: '2.5rem',
    borderRadius: 'md',
    bg: 'white',
    border: '1px solid',
    borderColor: 'gray.200',
    _hover: { borderColor: 'gray.300' },
    _focus: { borderColor: 'blue.500', boxShadow: '0 0 0 1px #3182ce' },
  },
  select: {
    height: '2.5rem',
    borderRadius: 'md',
    bg: 'white',
    border: '1px solid',
    borderColor: 'gray.200',
    _hover: { borderColor: 'gray.300' },
    _focus: { borderColor: 'blue.500', boxShadow: '0 0 0 1px #3182ce' },
  },
  formControllWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '2rem',
    mb: '1rem',
  },
  avatarSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: '1.5rem',
  },
  circleUpload: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '4.5rem',
    height: '4.5rem',
    bg: 'gray.50',
    borderRadius: 'full',
    border: '2px dashed',
    borderColor: 'gray.300',
    cursor: 'pointer',
    _hover: { borderColor: 'blue.400', bg: 'blue.50' },
    transition: 'all 0.2s',
  },
  imageUpload: {
    borderRadius: 'full',
    width: '4.5rem',
    height: '4.5rem',
    objectFit: 'cover',
    border: '2px solid',
    borderColor: 'blue.500',
    cursor: 'pointer',
  },
  formErrorMessage: {
    fontSize: '0.75rem',
    color: 'red.500',
    mt: '0.2rem',
  },
  buttonWrapper: {
    width: '100%',
    justifyContent: 'flex-end',
    gap: '1rem',
    pt: '1.5rem',
    borderTop: '1px solid',
    borderColor: 'gray.100',
  },
  button: {
    px: '2rem',
    height: '2.5rem',
    borderRadius: 'md',
    fontWeight: '600',
  },
};
